Update wallpaper scripts

diff --git a/bin/.local/bin/change-wallpaper b/bin/.local/bin/change-wallpaper
--- a/bin/.local/bin/change-wallpaper
+++ b/bin/.local/bin/change-wallpaper
@@ -1,7 +1,15 @@
 #!/usr/bin/env bash
 
+if [[ -d $HOME/personal/media/wallpapers ]]; then
+    wallpapers="$HOME/personal/media/wallpapers"
+elif [[ -d $HOME/wallpapers/ ]]; then
+    wallpapers="$HOME/wallpapers"
+else
+    echo "Error: wallpapers not found"
+    exit 2
+fi
+
 if [[ -f /usr/bin/nitrogen ]]; then
-    wallpapers="$HOME/personal/images/wallpapers"
     nitrogen $wallpapers
 # elif [[ -f /usr/bin/feh ]]; then
 #     images_folder=~/personal/images
