fix(scripts): check if hyprpaper exists

diff --git a/bin/.local/bin/change-wallpaper b/bin/.local/bin/change-wallpaper
--- a/bin/.local/bin/change-wallpaper
+++ b/bin/.local/bin/change-wallpaper
@@ -11,6 +11,10 @@ fi
 
 # On Wayland using hyprpaper
 if [[ -n $WAYLAND_DISPLAY ]]; then
+    if ! command -v hyprpaper > /dev/null; then
+        echo "Error: hyprpaper not found"
+        exit 1
+    fi
     selected=$(find "$wallpapers" | grep '.png\|.jpg\|.jpeg' | fzf)
     if [[ -z $selected ]]; then
         exit 0
diff --git a/bin/.local/bin/set-random-wallpaper b/bin/.local/bin/set-random-wallpaper
--- a/bin/.local/bin/set-random-wallpaper
+++ b/bin/.local/bin/set-random-wallpaper
@@ -11,6 +11,10 @@ fi
 
 # On Wayland using hyprpaper
 if [[ -n $WAYLAND_DISPLAY ]]; then
+    if ! command -v hyprpaper > /dev/null; then
+        echo "Error: hyprpaper not found"
+        exit 1
+    fi
     # shellcheck disable=SC2012
     ls "$wallpapers" |sort -R | tail -1 | while read -r selected; do
         echo "Setting wallpaper to $selected"
