feat(keyboard-layout): add wayland support

diff --git a/bin/.local/bin/keyboard-layout b/bin/.local/bin/keyboard-layout
--- a/bin/.local/bin/keyboard-layout
+++ b/bin/.local/bin/keyboard-layout
@@ -1,21 +1,37 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 if [[ -n $WAYLAND_DISPLAY ]]; then
-    echo "Error: Wayland is not supported"
-    exit 1
-fi
-
-# Set the keyboard layout
-if [[ -n "$1" ]]; then
-    if [[ "$1" == "--german" ]]; then
-        setxkbmap -layout de
-    # elif [[ "$1" == "--toggle" ]]; then
-    #     if [[ $(setxkbmap -query | awk '/^layout/ {print $2}') == "de" ]]; then
-    #         echo switching back to default;
-    #     fi
+    ###########################################################################
+    # WAYLAND
+    ###########################################################################
+    if [[ "$DESKTOP_SESSION" == "hyprland" ]]; then
+        # Toggle between us,ru and de
+        CURRENT=$(hyprctl getoption input:kb_layout | awk '/str/ {print $2}')
+        if [[ "$CURRENT" == '"de"' ]]; then
+            hyprctl keyword input:kb_layout us,ru > /dev/null
+        else
+            hyprctl keyword input:kb_layout de > /dev/null
+        fi
+    else
+        echo "Error: this wayland session is not supported"
+        exit 1
     fi
 else
-    # Use "localectl list-x11-keymap-options | grep grp:" to determine available keymap-options
-    setxkbmap -layout us,ru
-    setxkbmap -option 'grp:win_space_toggle'
+    ###########################################################################
+    # XORG
+    ###########################################################################
+    # Set the keyboard layout
+    if [[ -n "$1" ]]; then
+        if [[ "$1" == "--german" ]]; then
+            setxkbmap -layout de
+            # elif [[ "$1" == "--toggle" ]]; then
+            #     if [[ $(setxkbmap -query | awk '/^layout/ {print $2}') == "de" ]]; then
+            #         echo switching back to default;
+            #     fi
+        fi
+    else
+        # Use "localectl list-x11-keymap-options | grep grp:" to determine available keymap-options
+        setxkbmap -layout us,ru
+        setxkbmap -option 'grp:win_space_toggle'
+    fi
 fi
