Update my monitor-layout script

diff --git a/bin/.local/bin/monitor-layout b/bin/.local/bin/monitor-layout
--- a/bin/.local/bin/monitor-layout
+++ b/bin/.local/bin/monitor-layout
@@ -1,6 +1,16 @@
 #!/usr/bin/env bash
 
-# TODO: switch to /bin/sh
+## Functions
+check_if_command_exists() {
+    if ! command -v "$1" > /dev/null; then
+        echo "Error: $1 not found"
+        exit 1
+    fi
+}
+## End Functions
+
+check_if_command_exists xrandr
+
 # get info from xrandr
 connectedOutputs=$(xrandr | awk '$2 == "connected"{print $1}')
 # activeOutput=$(xrandr | grep -E " connected (primary )?[1-9]+" | sed -e "s/\([A-Z0-9]\+\) connected.*/\1/")
@@ -10,7 +20,6 @@ for display in $connectedOutputs; do
     monitors+=($display)
 done
 
-# Names: Dell(eDP-1-1,HDMI-1-1), Asus(edp, HDMI-1-0)
 intern=${monitors[0]}
 extern=${monitors[1]}
 
