feat(paccache-clear): require paccache installed

diff --git a/bin/.local/bin/paccache-clear b/bin/.local/bin/paccache-clear
--- a/bin/.local/bin/paccache-clear
+++ b/bin/.local/bin/paccache-clear
@@ -5,6 +5,11 @@
 # Script to clean pacman and paru cache
 # Requirements: paccache command from pacman-contrib package
 
+if ! command -v paccache > /dev/null; then
+    echo "Command 'paccache' not found. Please install pacman-contrib."
+    exit 1
+fi
+
 # Src: https://gist.github.com/ericmurphyxyz/37baa4c9da9d3b057a522f20a9ad6eba
 # Based on scripts from albertored11 and luukvbaal
 # https://gist.github.com/albertored11/bfc0068f4e43ca0d7ce0af968f7314db
